streams:
  stable:
    type: production
  testing:
    type: production
  next:
    type: production
  testing-devel:
    type: development
    default: true
  # next-devel:         # do not touch; line managed by `next-devel/manage.py`
    # type: development # do not touch; line managed by `next-devel/manage.py`
  rawhide:
    type: mechanical
    use_osbuild: true
  # branched:
  #   type: mechanical
  # bodhi-updates:
  #   type: mechanical
  # bodhi-updates-testing:
  #   type: mechanical

additional_arches: [aarch64, ppc64le, s390x]

source_config:
  url: https://github.com/coreos/fedora-coreos-config

s3:
  bucket: prod-account-match-fcos-builds
  # see bucket layout in https://github.com/coreos/fedora-coreos-tracker/issues/189
  builds_key: "prod/streams/${STREAM}"
  # just upload as public-read for now, but see discussions in
  # https://github.com/coreos/fedora-coreos-tracker/issues/189
  acl: public-read

#registry_repos:
#  oscontainer:
#    repo: quay.io/fedora/fedora-coreos
#    tags: ["${STREAM}"]
#  kubevirt:
#    repo: quay.io/fedora/fedora-coreos-kubevirt
#    tags: ["${STREAM}"]

versionary_hack: true

default_artifacts:
  all:
    - hashlist-experimental
  aarch64:
    - gcp
  ppc64le:
    - powervs
  s390x:
    - ibmcloud
  x86_64:
    - gcp

clouds:
  aws:
    bucket: prod-account-match-fcos-builds/ami-import
    primary_region: us-east-1
    # we make our images public in the release job via plume
    public: false
    # Accounts to share newly created AMIs with
    grant_users:
      - "013116697141"
  azure:
    test_resource_group: fedora-coreos-testing
    test_storage_account: fedoracoreostesting
    test_storage_container: fedora-coreos-testing-image-blobs
    test_architectures: [x86_64]
  gcp:
    bucket: fedora-coreos-devel-image-uploads/image-import
    description: "Fedora, Fedora CoreOS Devel ${STREAM}, ${BUILDID}, ${BASEARCH} published on ${DATE}"
    family:
      x86_64: "fedora-coreos-devel-${STREAM}"
      aarch64: "fedora-coreos-devel-${STREAM}-arm64"
    public: true
    licenses:
      # No "fedora-coreos-${STREAM}" licenses exist in the devel account
      # - "fedora-coreos-${STREAM}"
      - "https://compute.googleapis.com/compute/v1/projects/vm-options/global/licenses/enable-vmx"
  openstack:
    test_architectures: [x86_64, aarch64]

misc:
  generate_release_index: true
  run_extended_upgrade_test_fcos: true
